#+TITLE: New Emacs Config
* Starting Fresh
My [[https://codeberg.org/mbcc/emacs-config][old config]] is, well, old. I started it a long time ago and based it off of a systems crafters video.
I tried to keep everything separated to make it easier, which just blew up in my face. A lot of packages got thrown to
the wind and settled into random .el files.
Along with the bloat of a bunch of packages with purposes I didn't have a clue of. Copy and pasting a set-up is a quick
way to get confused. I replaced a lot of packages and tried to put them in fewer files.

* Important Installation Steps
** Jinx
Jinx can be installed from GNU ELPA or MELPA directly with =package-install=.

Your Emacs must be compiled with dynamic module support. Furthermore a C
compiler must be available on your system (=gcc= or =clang=). Jinx requires
=libenchant=, which is needed to compile the native module at install time. If
=pkgconf= or =pkg-config= is available, Jinx will use it to locate =libenchant= during
installation. Depending on your BSD or Linux distribution you have to install
different packages:

- Debian, Ubuntu: =libenchant-2-dev=, =pkgconf=
- Arch, Gentoo: =enchant=, =pkgconf=
- Guix: =emacs-jinx= defined in =emacs-xyz.scm=
- Nix: =jinx= defined in =elpa-packages.nix=
- Void: =enchant2-devel=, =pkgconf=
- Fedora: =emacs-jinx= or =enchant2-devel=, =pkgconf-pkg-config=
- OpenSUSE: =emacs-jinx= or =enchant-devel=, =pkgconf-pkg-config=
- FreeBSD, OpenBSD, Mac: =enchant2=, =pkgconf=

*** Dictionaries/Languages
Jinx requires Dictionaries to function properly. The correct packages to install varies
from distro to distro, obviously.
- OpenSUSE: =nuspell= is what helped me, although I believe it was the dependencies that fixed it.
* Lisp Files
These are my main config files, each serving a different purpose
** keybinds.el
To store my keybindings in one central place. 
using the [[https://github.com/emacs-evil/evil][Evil]] mode for vim-emulation and which key to show helpful hints.
View the file for all keybindings, they are pretty self explanatory. 
** system.el
This file is short, used to change some Emacs features like making backup files.
*** Vterm
decided to install vterm again. eat is lighter but I'm just too used to the vterm workflow

** user-interface.el
This is the biggest file and change in the new /config/.
*** Vertico
This [[https://github.com/minad/vertico][package]] is a completion framework with a few built-ins, the one I use is vertico-directory to make
find-file better looking. Along with orderless completion style.
*** Consult
This [[https://github.com/minad/consul][package]] is an almost one-to-one drop in for counsel, which I replaced for consult, that supports live-viewing for search and
navigation. It has a lot of other powerful features that I need to explore more.
*** Corfu
A light weight popup [[https://github.com/minad/corfu][library]] to make in-buffer completion look better. 
